name: Bhutan
favicon: null
layout_spectrum: 0.2447
typography_spectrum: 0.31985
title: Utazzon Bhutánba Valcsicsák Zoltánnal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#35475f'
    - '#ffffff'
    - '#cb893f'
    - '#973818'
    - '#d0c4b8'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
